### ISSUE TITLE
Minigames Compatiblity

### ISSUE THREAD

**Issue by KevinEssence** [sgtcaze/NametagEdit#128]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.0.3

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
https://gyazo.com/7903198f7bb1ed1abda9ad943de4fe6c

### What plugins are you using? Type /plugins
Essentials and Minigames

### Please explain your issue?
I notice with the minigames plugin, in team based minigames, it likes to change their color in tab list to the team name color. Once the game ends it makes their name white and they need to relog for name tag edit to give them their prefix and color back. Is there a fix for this?

### How do you reproduce the issue?
Play the minigame and when it ends your name will be white and it will require you to relog

### Is there an error(s) in the console? Please use: https://pastebin.com
No errors

**Comment by sgtcaze** [comment]
Unfortunately this is not within the scope of NametagEdit. Due to how scoreboards are implemented, we cannot reliably anticipate overrides from minigames or plugins that alter scoreboards/packets like we do. (e.g. there's no real way we can mark our packets, and disregard others without some complex logic.)
