### ISSUE TITLE
Person Prefix Disappearing

### ISSUE THREAD

**Issue by BoostedNetwork** [sgtcaze/NametagEdit#139]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
4.1.4

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
This server is running Paper version git-Paper-1060 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
https://gyazo.com/5eb841d857ecfeef3ea70978bd4f1b88

### Please explain your issue?
When you login to the server, your Rank on tab will be fine for everyone, until you hold down tab long enough to update, and when it does your person prefix disappears but it will stay for everyone else on their tabs.
Example: http://i.imgur.com/l0XT5dW.jpg

### How do you reproduce the issue?
I could only reproduce this issue on one of my servers, how to do it, is explained above.

### Is there an error(s) in the console? Please use: https://pastebin.com
No Errors and no obvious signs in debug mode.

**Comment by DownUndaDevGames** [comment]
I get the same thing. And I get this screen when I try to log in some times: https://gyazo.com/75727badb60c4509409fbe921d1c85e6

**Comment by BoostedNetwork** [comment]
@AliumCraft I have the same issue, this is from my logs: http://pastebin.com/hBDWVutx

**Comment by sgtcaze** [comment]
The "Citizens" plugin clashes with NametagEdit. What happens is that, when a player shares the same name as an NPC, when Citizens clears the NPC from the tab list, it kills the nametag for the online player as well.

**Comment by xboy1994** [comment]
I am having the same bug with my server. Spigot 1.11.2 

My Plugins: ![Plugins](!http://i.imgur.com/HFwIugZ.png)

**Comment by BoostedNetwork** [comment]
@sgtcaze Anyway to alter Citizens config in order to disable the plugin clash.

**Comment by sgtcaze** [comment]
I know which packet is causing it: PacketPlayOutPlayerInfo.

I made multiple attempts to listen to that packet, and prevent it from clearing the nametag. The issue is that, if you have an NPC with the same name as the player, 2 names will pop up in tab: the npc and the real player (if online). Citizens tries to remove the NPC tab list entry, but in doing so it also removes the legitimate player's tag.

This is because mojang thinks: if you have the same entity name as a scoreboard entry or game profile display name, you MUST be the same entity. However, this is flawed as it doesn't consider the UUIDs of either NPC or the player.
