### ISSUE TITLE
Sorting Issue and names getting cut off

### ISSUE THREAD

**Issue by SwiftSwamp** [sgtcaze/NametagEdit#152]
### What version/build of NametagEdit are you using? Type /ver NametagEdit
Version 4.1.4, latest Dev Build on Jenkins, just downloaded it moments ago.

### What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver
Tested on both PaperSpigot 1.11 and 1.8.x latest.

### What plugins are you using? Type /plugins
Only plugin that I am using that modifies the scoreboards or tab are Tab v5.10 and Featherboard v3.17

### Please explain your issue?
https://s27.postimg.org/albjubqz7/test.png Picture explains it all.
Sometimes names will also get random formatting like bold, or magic, etc... it's really strange. I never had a sorting problem, I stopped using NTE for a while, came back and now it doesn't work. It use to work back on build 46 that I was using for the longest time.

### How do you reproduce the issue?
Heres my config: https://pastebin.com/C173TMj3

### Is there an error(s) in the console? Please use: https://pastebin.com

**Comment by sgtcaze** [comment]
This is because nametags like: **&3Bl&bizza&3rd &3** are 17 characters long, where as the max is 16 characters long. NametagEdit will pull the first 16 characters (otherwise the scoreboard will crash everyone online). 

It would look something like: **&3Bl&bizza&3rd &**. Then, when the nametag is formatted by minecraft in the tab, that dangling & will attempt to colorize with the next available character. Example: **&3Bl&bizza&3rd&** + **Bob** will use the Aqua color and you will be left with "ob" instead of "Bob" at the end. Does this make sense?

As a result, this is not something we can fix, sadly. Just plain old minecraft.
