### ISSUE TITLE
Refresh Time

### ISSUE THREAD

**Issue by Spazzinq** [sgtcaze/NametagEdit#174]
### This is a feature request

Hello, developers of NametagEdit, I would like to request a refresh timer for nametags due to placeholders not updating until I reload the plugin. I use this for my factions server and I would really like if there was a option to refresh the nametags or placeholders because if a player edits their faction name or disbands it the plugin doesn't update the nametag until I reload nametagedit.

--
Thanks,
Spazzinq

**Comment by sgtcaze** [comment]
Thank you for the suggestion. I have added a configurable interval.

**Comment by Spazzinq** [comment]
@sgtcaze I just thought of something. ***If*** there is an event for when a placeholder is updated in PlaceholderAPI, couldn't that be a much more simple way to know to update the nametag instead of a timed refresh? Wouldn't that use less resources too?

**Comment by sgtcaze** [comment]
The issue is that even the Placeholder plugins do not know when a Placeholder has changed. I could create a Placeholder that formats based off the current system time, but the PlaceholderAPI wouldn't know when, unless my plugin triggered an event - and relatively no plugins provide this functionality.

**Comment by Spazzinq** [comment]
Okay, thanks for educating me :)
