### ISSUE TITLE
citizens

### ISSUE THREAD

**Issue by ghost** [sgtcaze/NametagEdit#181]
**I'm sorry, I'm not good at english
citizens ? paperspigot1.11.2
I do not want it to show up on npc :(
Here is the picture: https://ooo.0o0.ooo/2017/07/10/5962531e37562.png
I hope you can help me solve this problem！
Thank you :)**

**Comment by sgtcaze** [comment]
We cannot control this default behavior for the client, sadly. If the name is the same in Tab/Nameplate/Scoreboard then it will share the same nametag regardless. The NPC you spawned is almost indistinguishable from your normal player NPC because it uses the same display name, skin properties etc.

I am not sure if we can modify the metadata for the entity via ProtocolLib, but it might be possible if we know the Entity ID ahead of time.

**Comment by ghost** [comment]
Ok ... there is no such situation when i use the paperspigot 1.10.2

**Comment by JustOneMoreBlock** [comment]
Alternate Solution:
- /npc create anyplayername (You can use like an alt. multiple times.)
- /npc skin theplayer (This should use the same UUID as anyplayername, but show the skin you want.)
- /npc name or nick (This should use the same UUID as anyplayername, but show the skin you want.)

I don't think you would be 1.11.2 and downgrade your server to 1.10.2 - This would cause too many issues with a possible world corrupt and plugin issues.
