### ISSUE TITLE
getting cuted

### ISSUE THREAD

**Issue by MemesIsRuthless** [sgtcaze/NametagEdit#185]
for some reason sometimes the tag cant be very long
like i just did &f[&2builder&f] &2 but instead in tab and above player says the player name is white, but if i remove the space it will be green. then tried more and some of my ranks are getting cut like example
&f[&3&lTITAN&f] Memes
it becomes like 
[TITAN]emes
plus the tags keep on disapearing i always must do /nte reload for the tags to come back

**Comment by JustOneMoreBlock** [comment]
Hello,

Let's take a look at your issue!

```
&f[&2builder&f] &2
```
This is 18 characters.

```
&f[&3&lTITAN&f] Memes
```
This is 21 characters.

&f = +2
Any spaces = +1

Unfortunately, this is not a bug. This is a Minecraft limitation that Mojang has implemented. The max character count is 16. This includes any color codes and spaces.

This is what I would do for builder:
```
[&2builder&f] &2
```
Removing the first `&f` because it's white by default. :)

You would have to re-think Titan Memes.
