### ISSUE TITLE
NameTagEdit starts using GM prefixes on tablist

### ISSUE THREAD

**Issue by D4RKQuadricos** [sgtcaze/NametagEdit#191]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.0.1

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
1.8.8 Spigot

**What plugins are you using? Type /plugins**
Tablist, NTE

**Please explain your issue. How do you trigger it?**
The Tablist works good but when a player leaves or joins the tablist prefixes are dying
and starting using GM prefixes, shouldnt it use GM prefixes ?

**Are there any errors in the console? Please use: https://pastebin.com**
NOPE

**Comment by sgtcaze** [comment]
NametagEdit uses two Placeholder plugins which other plugins can interact with and fetch data from. NametagEdit itself does not hook into other plugins such as GroupManager except for when we listen to permission changes.

It sounds like your issue is a conflict of two plugins. You want NametagEdit to control the tablist right? Or is your Tablist plugin supposed to control the tab?
