### ISSUE TITLE
1.12.1

### ISSUE THREAD

**Issue by Zed9K** [sgtcaze/NametagEdit#195]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

Spigot 1.12.1-R0.1-SNAPSHOT

**What plugins are you using? Type /plugins**

http://i.imgur.com/BJL4rKg.png?1

**Please explain your issue. How do you trigger it?**

the plugin was working well, until i upgraded to 1.12.1
i was on 1.12
so now its not working ... the plugin is Green in the /pl list
but its not working ... when i do /nte group list
it say ( **Loaded Groups** ) and then nothing
just **Loaded Groups**
The Plugin is working, but its not loading any of the groups.... what should i do ?

**Are there any errors in the console? Please use: https://pastebin.com**

there is nothing in the console ..

**Comment by sgtcaze** [comment]
Apologies for being very late, but NametagEdit was updated to [1.12 pre-5 on May 28](https://github.com/sgtcaze/NametagEdit/commit/a5c617cb128085a6edba7439bdf269adfbe1e5d0). No NMS changes to the Packet class have been made since then. So the only thing that breaks between versions appears to work, even in mid October 2017 using spigot 1.12.2 (5 months later).

If you use our plugin and your issues have since disappeared, that's great!

If you stopped using NametagEdit, we could still help others by fixing this potential issue. Albeit, I am unable to find this issue (just tested on my environment.)

Please reopen if you like.

**Comment by Zed9K** [comment]
Don't worry it wasn't a plugin problem, sorry for not closing it
my problem was, that i added MySQL data in the Config File
and i forgot to reset the groups :thinking: :P
