### ISSUE TITLE
Invisibility potion 

### ISSUE THREAD

**Issue by bradyrenting** [sgtcaze/NametagEdit#197]
# Bug Report

**Please explain your issue. How do you trigger it?**

When a player uses an invisibility potion people will still see their nametags.

**Comment by PhanaticD** [comment]
i am having this issue as well

**Comment by sgtcaze** [comment]
What version of minecraft client and server? If the client is 1.8 or below, it ignores the bit flag that allows you to see nametag visibility. If so, this is a minecraft bug [we have discussed before](https://github.com/sgtcaze/NametagEdit/issues?utf8=%E2%9C%93&q=invisibility).

If not, do you use the AntiPush feature? If so, I think teamed players might be able to see nametags since the nametag visibility is set to ALWAYS. You can [see that here](https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/packets/PacketWrapper.java#L35).
