### ISSUE TITLE
Name tagging anything shows the prefix? Whaaa...?

### ISSUE THREAD

**Issue by BelleGoBelle** [sgtcaze/NametagEdit#209]
# Bug Report

**Type /ver NametagEdit and post the output.**

Version 4.1.7

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

This server is running CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**

Plugins (51): BlockParticles, Questioner, ClearChat, PlaceholderAPI, GroupManager, NametagEdit, FatPort, Broadcaster, RewardVoting, ServerLinks, Tablist, LightAPI, WorldEdit, FirstJoinPlus, SmartSpawn, DisableJoinMessage, ActionHealth, Votifier, ProtocolLib, ElsweyrsHeads, DoubleJumpPlus, SimpleHelpOp, Vault, ServerListPlus, ChairStairs, LightSource, Parties, LWC, HolographicDisplays, WorldGuard, Brewery, CustomMobs, PetBlocks, CratesPlus, Essentials, MarriageMaster, Citizens, Magic, CustomGUI, MobMoney, EnjinMinecraftPlugin, ArmorStandTools, Quests, Duels, CommandNPC, Towny, RandomTP, TownyChat, CS-CoreLib, TownyNameUpdater, QuickMarket

**Please explain your issue. How do you trigger it?**

It's whenever someone names a mob / animal. The actual prefix shows above the mob/animal as the prefix and still has the mobs name. I'm not sure how to fix this and I've looked in Config. There's nothing that I can fix unless I'm blind.

**Are there any errors in the console? Please use: https://pastebin.com**

There is no errors.

**Comment by BelleGoBelle** [comment]
EDIT: It's only for Tamed Cats and Dogs... Plus,It's been two weeks and no response. My server is being released very shortly and I'm a bit worried that this won't be fixed.

**Comment by sgtcaze** [comment]
Apologies for the delay. It works for **any** tamed animal. Unfortunately this is not exactly an issue with NametagEdit I can easily fix. The issue is that Mojang likes to use UUIDs/DisplayNames as identifiers for entities/scoreboards, so what is likely happening is that the tamed animal has a UUID referenced to the owner, and its using the prefix associated with the player.

Presently, I am not sure how to get around that. I looked around the Entity code from the server and played around with the display name. I'll update this if I find something.

**Comment by BelleGoBelle** [comment]
Okay. Thank you for responding and getting back to me. Please let me know if this bug is solved anytime soon. I am reporting back to a few other servers since I asked them for help on this issue. Thank you :D

**Comment by Saidas25** [comment]
i know, this is a bit late, but i have the same issue, any fix?
