### ISSUE TITLE
Error if I have a lot of characters

### ISSUE THREAD

**Issue by LagBug** [sgtcaze/NametagEdit#222]
# Bug Report

**Type /ver NametagEdit and post the output.**

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
![image](https://user-images.githubusercontent.com/25084277/34390124-6d8e5f8e-eb46-11e7-8853-5d3249b05812.png)

**What plugins are you using? Type /plugins**
Not allowed to see.

**Please explain your issue. How do you trigger it?**
In the groups.yml is setted up 2 groups, Owner and Mod.. The prefixes are: '&8[&4&lOwner&8] &7' and for the Mod: '&8[&cMod&8] &7' Now, the Mod works while the Owner doesn't.. I know it doesn't work because i have more characters in the Owner.. I figured out that because I changed '&8[&4&lOwner&8] &7' to '&8[&4&lOwn&8] &7' and it worked! Thanks and hope you will fix it! 

**Are there any errors in the console? Please use: https://pastebin.com**

Nope, there are no errors

**Comment by sgtcaze** [comment]
The 16 character limit is hard coded because this is the maximum length we can make it -- otherwise clients crash. You may notice some servers allow very long nametags. This is because they use the TabListName, while we use scoreboards. In newer versions of nametagedit, [we lifted the restriction](https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/com/nametagedit/plugin/NametagHandler.java#L406) on 16 character PlayerListNames because in later versions of Minecraft this limitation was increased. It wasn't always this way - if I recall correctly in 1.6/7 if you had a PlayerListName longer than 16 characters the client would crash. 

Question: Is the nametag being cut off in Tab or above the player's head?

**Comment by LagBug** [comment]
I think/believe that the chat colors should not get included? Is there any way I can fix this? 
And about your question its like not taking care of the "&7"

**Comment by sgtcaze** [comment]
I have introduced a new feature called "LongTags". Please reopen the issue if this does not satisfy your requirement.

Long Tags Disabled:
![long_tags_disabled](https://user-images.githubusercontent.com/4266612/34426094-bfb3436e-ebe7-11e7-953b-b49badac31f8.png)

Long Tags Enabled:
![long_tags](https://user-images.githubusercontent.com/4266612/34426108-c8f9d488-ebe7-11e7-9fa8-810468975080.png)

Please note, that LongTags does not apply to the Nameplate (the name above the head) because of the default limitation in Minecraft.

Edit: See the documentation or tryout /nte longtags and then /nte reload

**Comment by LagBug** [comment]
Thanks again! But I got one problem: I can't find where to enable LongTags... Is it an option in config.yml or what?

Thanks!

**Comment by sgtcaze** [comment]
It is an option in the config, yes. Alternatively, you can do:
/nte longtags
and then
/nte reload

**Comment by LagBug** [comment]
In the spigot version, I can't find the /nte longtags
Is there any updated version?

**Comment by sgtcaze** [comment]
We have a build server for early releases

http://ci.nametagedit.com
