### ISSUE TITLE
Continued problem

### ISSUE THREAD

**Issue by Pabsb** [sgtcaze/NametagEdit#232]
# Bug Report

**Type /ver NametagEdit and post the output.**

NametagEdit version 4.2.0
Authors: sgtcaze and Cory

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

1.8.3-R0.1-SNAPSHOT

**What plugins are you using? Type /plugins**

WordEdit, killStats, NametagEdit, Holograms, WorldGuard, MVdWPlaceHolderAPI, PermissionsEx, FeatherBoard, ViaVersion, mcMMO, KeepTheWeather, Vault, HideStream, InfiniteBlocks, CombatTagPlus, EssentialsX, EssentialsXChat, EssentialsXSpawn, EssentialsXGeoIP, Protocollib, NoCheatPlus, CompactNoCheatPlus, PNCP

**Please explain your issue. How do you trigger it?**

https://imgur.com/a/c5yS4
With your answer to my old issue #225 you said to look at #222 for help but I still don't know how to get the long name tags above the players head but it works in tablist while in your image both work: https://user-images.githubusercontent.com/4266612/34426094-bfb3436e-ebe7-11e7-953b-b49badac31f8.png Is there a plugin I need to add or something to make this work?

**Are there any errors in the console? Please use: https://pastebin.com**

None

**Comment by sgtcaze** [comment]
Apologies for the super late reply. What I was trying to communicate is that LongTags has no effect on your nametag above your head. This is because this limit is imposed by Mojang with respect to the PacketPlayOutScoreboardTeam. 

Basically, Mojang says 16 characters max for prefix and suffix. The tab list has different limits, as you can see. We hoped for years Mojang would change this, but they did us one thing worse and made 1.13 a nightmare for our plugin.
