### ISSUE TITLE
Long Tag Function

### ISSUE THREAD

**Issue by johnsoncui02** [sgtcaze/NametagEdit#247]
Unsure what kind of report this is.

NTE Version:
![image](https://user-images.githubusercontent.com/23487437/36427350-db2c9926-1601-11e8-9473-44828b6a2304.png)

Spigot VersionL
![image](https://user-images.githubusercontent.com/23487437/36427368-e5ba96ae-1601-11e8-8423-79db696f5fef.png)

Possibly Conflicting plugins: Chat Control, Chat Format, 

Explaination:
It seems that the long-tag function works for the tablist but not the person's name that's on top of the player.

![image](https://user-images.githubusercontent.com/23487437/36427335-d16b30b4-1601-11e8-8a3c-d5af934aaa59.png)
![image](https://user-images.githubusercontent.com/23487437/36427853-1bf9a29a-1603-11e8-8500-e31848bb0464.png)

No errors on Console.

**Comment by sgtcaze** [comment]
Here's from our FAQ:

**Q: My nametag is cut short, even with LongTags enabled!**
**A:** LongTags is only able to disable a longer nametag in the tablist. The name above your head has a different limit (16 characters for prefix and suffix.) We are unable to change this, as this limit is imposed by Mojang.

Unfortunately this is not something we can fix. There was this idea we could use floating entities for nametags (albeit very messy and could be very invasive). There was also an idea where the player could have a nametag different from tab and above their head.

We're still circling some of these ideas... but it might not matter since 1.13 virtually destroys NametagEdit.

**Comment by Golicraft** [comment]
@sgtcaze I like the idea with two different nametags. One in the tablist and another over the name. You should do that. Very creative and good idea. Thank you in advance :)
