### ISSUE TITLE
Prefix/suffix colors removed when server is closed

### ISSUE THREAD

**Issue by Spirit55555** [sgtcaze/NametagEdit#25]
In the latest commit, colors are removed from the prefix/suffix when the server is closed. This is very annoying.

See here: https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/ca/wacos/nametagedit/core/NametagHandler.java#L136

**Comment by ShadowRanger** [comment]
I can confirm this as I am having the same problem. I also think I know why it's occurring. As you pointed out, the problem is within the saveFileData() method in the NametagHandler. Basically, the 'Order' section of the groups file is being overridden and replaced with an empty List. Additionally, the prefix's and suffix's are being stripped of colours. Here are the links to the specific lines of code that this is being done:

https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/ca/wacos/nametagedit/core/NametagHandler.java#L140

https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/ca/wacos/nametagedit/core/NametagHandler.java#L146-147

https://github.com/sgtcaze/NametagEdit/blob/master/src/main/java/ca/wacos/nametagedit/core/NametagHandler.java#L153-154

**Comment by sgtcaze** [comment]
@Lolmewn was awesome and fixed the issue in the latest commit.
