### ISSUE TITLE
Displaying the wrong prefix

### ISSUE THREAD

**Issue by FiRe33Gaming** [sgtcaze/NametagEdit#282]
# Bug Report

**Type /ver NametagEdit and post the output.**

4.2.0

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**

version 1.11-RO.1-SNAPSHOT

**What plugins are you using? Type /plugins**

https://pastebin.com/F7s99pp2

**Please explain your issue. How do you trigger it?**

I have GManager , example: vip grade has default grade inheritance so the default prefix permission (nte.default) but vip grade hat nte.vip permission but it's the default prefix who is displayed
The priority of the vip grade is 1 and default 10

**Are there any errors in the console? Please use: https://pastebin.com**

No Error

**Comment by JustOneMoreBlock** [comment]
Hello,

In your GroupManager, on your `default` group keep `nte.default`. However, since your `vip group` inherits `default group` your issue is you're getting the `default tag`? Then simply provide the `vip group` the `nte.vip` permission node, and negate `nte.default` on the `vip group`.

Example:
```
groups:
  default:
    default: true
    permissions:
    - nte.default
    inheritance: []
    info:
      prefix: ''
      build: false
      suffix: ''
  vip:
    default: true
    permissions:
    - -vip.default
    - nte.vip
    inheritance:
    - default
    info:
      prefix: ''
      build: false
      suffix: ''
```
