### ISSUE TITLE
Request or Bug (something)

### ISSUE THREAD

**Issue by termanator1128** [sgtcaze/NametagEdit#31]
Hi im using a plugin which lets me disguise as someone else plugin located here https://www.spigotmc.org/resources/randomdisguise-skript.20663/ and i need to be able to keep my nametag prefix and suffix so i can be hidden but it doesnt stay but if i do the command /ne prefix/suffix it works but says cant find the uuid for %s and doesnt show up in tab which i need to

**Comment by JustOneMoreBlock** [comment]
You have your group or prefix/suffix as your normal account.
You disguise as a player.
You lose your group or prefix/suffix as a disguised player.
You want us to remember your normal account's group or prefix/suffix on the disguised player?

While this sounds cool, I believe this might be out the scope of our plugin.

However, since you're using Skript you can probably do the same thing by reading our files or database and update the prefix's based on your prefix/suffix.

**Comment by termanator1128** [comment]
Do you know how to do that?

**Comment by JustOneMoreBlock** [comment]
Unfortunately, I do not.
