### ISSUE TITLE
Reload when someone disguises using SonarPet

### ISSUE THREAD

**Issue by comfysquirrel** [sgtcaze/NametagEdit#32]
When disguising with [SonarPet](https://github.com/TechzoneMC/SonarPet), your nametag loses it's formatting until reloading NTE. Is it possible to listen for when a player disguises and reload NTE automatically?

**Comment by Chalwk** [comment]
I have the same issue with SonarPets.

[Premium Vanish ](https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/) does the same thing if you have **[hidden]** suffix enabled for the tablist in the config. Additionally, switching worlds (with multiverse) can cause the formatting to disappear. This also occurs with [PvP Manager](https://www.spigotmc.org/resources/pvpmanager.10610/) - regardless if Combat Tagging is enabled or not.

**Comment by sgtcaze** [comment]
I'll take a look into SonarPet when I have a chance. I am sure there's a way we can get around this issue. Followup soon.

**Comment by JustOneMoreBlock** [comment]
Tested: SonarPets - Cannot reproduce. Likely has been fixed in the newer version of SonarPet.
Premium Vanish - Appears they did have a HikariCP out of date on there BungeeCord, try updating to the latest version.
PvPManager - New version has been released. Please try the latest version.

If any of the issues persist, please create a new issue for each plugin.

Tested on Build 30.
Tested on Spigot 1.9.4
