### ISSUE TITLE
Nametag prefix cut off

### ISSUE THREAD

**Issue by 6IU** [sgtcaze/NametagEdit#330]
# Bug Report

**Type /ver NametagEdit and post the output.**
4.40

**What version of Bukkit/Spigot/PaperSpigot are you using? Type /ver**
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**What plugins are you using? Type /plugins**
Arconix, FAWE, PluginSpoof, PermissionsEx, DiscordCommand, NametagEdit, HolographicDisplays, Vault, GUIWarps, SilkSpawners, ShopGUIPlus, Worldedit, ASkyBlock, Essentials, EssentialsChat, Multiverse-Core, TitleManager

**Please explain your issue. How do you trigger it?**
No idea what triggered it, but players prefix in their nametag is cut off, here for example (the image), the ending bracket and space are cut off, but on tab, it's fine.
![2019-01-07_02 28 20](https://user-images.githubusercontent.com/45064480/50738148-fc264580-1224-11e9-898e-0d9da9cd6e97.png)

**Are there any errors in the console? Please use: https://pastebin.com**
No (other then ones coming from shopguiplus and warp gui upon startup)

**Comment by JustOneMoreBlock** [comment]
Hello,

Since your using 1.8.x your tag is limited to 16 characters. This includes any colors and bolds.
```
&f&l(&c&lOwner&f&l)
```
Colors and Bolds count as 2 characters each. This total amount is 19.

Tabs don't have any limits.

I usually do:
'&c&lOWNER &r'
This would be 12. The purpose of the space is so it's not directly by your name.
