### ISSUE TITLE
The Prefixes

### ISSUE THREAD

**Issue by Kaczmo** [sgtcaze/NametagEdit#76]
Hey so when I uninstall the plugin the Prefix/Suffix's are still active when there is no plugin downloaded into the Folder, when I reinstall it I cannot change/delete the prefixes I am looking to use the plugin but it seems to not work

**Comment by sgtcaze** [comment]
What Minecraft version are you using?

**Comment by Kaczmo** [comment]
Spigot 1.8, Using ViaVersion 1.8 - 1.9

**Comment by sgtcaze** [comment]
Very strange. This is definitely an issue with Minecraft 1.5 and 1.6 if I recall correctly. Did you unload with a plugin manager, or hard restart the server? In later versions of MC this wasn't an issue (nametags not being removed on refresh).

**Comment by Kaczmo** [comment]
restart the server

**Comment by sgtcaze** [comment]
And are you absolutely sure the nametags persist? Was the NametagEdit.jar and NametagEdit folder removed?

**Comment by Kaczmo** [comment]
Indeed, I even tried to reinstall it, plugin works but when you try to change any prefixes/suffix does not change and when you remove the plugin it still stays there

**Comment by sgtcaze** [comment]
Alright let's try the following:
- Stop server
- Make a copy of the server
- Delete the playerdata and stats folders in your world folder (the copy)
- Make sure NametagEdit is removed (make sure with /pl)
- Start the server

Do the tags persist?

**Comment by Kaczmo** [comment]
Doesn't work

**Comment by Kaczmo** [comment]
https://gyazo.com/62697fe26cef823ee1a43df0a5c2ad44 Plugins

**Comment by sgtcaze** [comment]
On your server copy, let's delete EVERY plugin and see if it persists. Then slowly start adding back plugins. I highly doubt NametagEdit is responsible for this on a 1.8 server. NametagEdit has been used on hundreds of servers without this issue.

**Comment by Kaczmo** [comment]
Okay, I will delete EVERY single plugin, when I get back school, lets just pray this will work, because I would love to use your plugin!, also when I get it working how can I set it up so once a player moves rank their nametag will change aswell? I'm using Pex

**Comment by sgtcaze** [comment]
This is already a feature @Kaczmo. Hopefully you can use NametagEdit no problem!

**Comment by Kaczmo** [comment]
None of the plugin is causing the issue

**Comment by sgtcaze** [comment]
Well just recapping
- Spigot 1.8
- Deleted playerdata/stats folders
- Deleted plugin/reinstalled
- Hard restarted
- Deleted plugins individually, no effect

This was 100% an issue in 1.5 minecraft because scoreboard data was stored in individual player profiles. If the conditions are as you described, then I am unable to help you. I do not think NametagEdit is responsible for these issues.

It's odd how with 0 plugins and your world data folder deleted the tags still persist. Either way, I will close this issue as it is not a NametagEdit bug. If you want further help you can add me skype "sgtcaze".

One thing I forgot to ask, are you using BungeeCord? Do you have  a BungeeCord plugin that modifies the tablist? That's the only explanation left.
