### ISSUE TITLE
Unorginized Listen Player Tab Tag

### ISSUE THREAD

**Issue by ofirtim** [sgtcaze/NametagEdit#90]
I am using the newest current version which is 4.1.2
i am using Spigot 1.8.6 build git-Spigot-044d928-e8c6403 R0.1 SNAPSHOT (496 Versions Behind)

Pretty Much owned Customized plugins that shouldn't interrupt NameTagEdit

Explaination:
Basically i use the /nte command as a dispatched command, but its not the problem... the problem is its sets me a suffix in personal suffix, now i have permissionable NTE that is prefix only, now when i try using the personal suffix its suddenly removes the permissionable Prefix.

No Errors came all along until now!

**Comment by sgtcaze** [comment]
Ah I get what you're saying. You have a Group that has a special Prefix, and you want a custom Suffix for a player. However, the Group prefix is being "removed" when the suffix is applied.

This is not a bug, this is the intended behavior. NametagEdit prioritizes Player tags over Group tags. They do not, and cannot overlap.

This is why we have the NametagEdit API - which allows developers to dynamically adjust this. The problem here is that in order to accomplish this with the plugin, you would need an intricate permissions setup and the core of the plugin would need to be rewritten.

**Comment by ofirtim** [comment]
soo basically its me Recodding your current plugin or i use your NameTagEdit API..? but its too work hard thingy, can't i use the same Priority as groups and Custom NTE's?

**Comment by sgtcaze** [comment]
No you cannot use the same priority, because it doesn't make sense. For example, if you had a custom nametag and group with both trying to be first, which one would be first?

**Comment by ofirtim** [comment]
well, soo you say i should use the API then? welp, that's cant be Cancelled unless i make Reflections... and thats gonna take A LONG TIME, soo i gonna use the API its self... thanks for the help
